### ISSUE TITLE
Love it!

### ISSUE THREAD

**Issue by kevinpapst** [alexleach/DompdfRendererBundle#1]
Can you tag the repository please, so it can be found easier.

You can add them in the "About this repository" scree, where you already added the description.

Now If you could select some tags (Topics), that would make it much easier for others to find it:

<img width="633" alt="Bildschirm­foto 2023-03-04 um 16 12 33" src="https://user-images.githubusercontent.com/533162/222913889-b5abf467-c1ae-4fde-beb0-aa4b2b7fa1ab.png">

I link these topics e.g. from the Kimai Marketplace. Thanks for sharing your plugin 👍

**Comment by alexleach** [comment]
Hi Kevin, thanks for looking in and for your suggestion 🙂 !

I've just added your suggested tags, and added a couple extras. I've also got a pretty awesome template now, so will upload that when I get a chance. I'm currently using it on the kimai-v1 branch, as the docker hub images (I'm using kimai/kimai2:fpm) run kimai v1.x, which is confusing because kimai2 is in the image name...

Anyway, thanks again for checking in! Please feel free to link this to the Kimai Marketplace, if that's not automatically enabled with the new tags. 😄 

I'll close this now, but I do still have a couple of outstanding queries which you might be able to help with? Not sure the best channel to contact you for help though... Maybe I should create an issue here, and then do you mind if I tag you in it?

**Comment by kevinpapst** [comment]
Yes, the naming is confusing. This will hopefully vanish, once everyone is running 2.x 😁 
It was a mistake to call it Kimai2 in the beginning, which I removed everywhere I could.
But the docker images might still use it. I am not a Docker user whatsoever, so I am blind on that eye.

If you want to add your plugin to the Marketplace, your are welcome! 
The website is, especially due to the tooling with Jekyll and multi-language support, rather complicated... but if you create the basic information, I will take care of the rest: https://www.kimai.org/documentation/store.html
